### ISSUE TITLE
UI: Terminal Output Issues / QoL Requests

### ISSUE THREAD

**Issue by valkyrienyanko** [Kittens-Rise-Up/client#8]
## Dragging
You can only drag the terminal output vertically if you are grabbing the text. You should be able to grab from anywhere and move the terminal output up and down.

## Snap to Bottom
If you drag the terminal output up, it will not snap back to the bottom as this has not been implemented yet.

![image](https://user-images.githubusercontent.com/6277739/130510726-c26a82e9-963e-479d-a42f-e99d2c8e228c.png)

**Comment by masonwoodford** [comment]
Can I give this a shot?

**Comment by valkyrienyanko** [comment]
Go ahead, I won't be editing the main unity scene for the next 12 or so hours.
